language: swift
osx_image: xcode11.3
script:
  - xcodebuild build -project FoodieSearch-rx.xcodeproj -scheme FoodieSearch-rx -allowProvisioningUpdates
  - xcodebuild test -project FoodieSearch-rx.xcodeproj -scheme FoodieSearch-rx -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3'